### ISSUE TITLE
Add Actual Imba Logo to landing page.

### ISSUE THREAD

**Issue by iamtirado** [athif23/start-imba#10]
Here's the [logo](https://user-images.githubusercontent.com/13579055/65052242-70101480-d994-11e9-9224-5ba4f50e8590.png)
![imba-logo](https://user-images.githubusercontent.com/13579055/65052242-70101480-d994-11e9-9224-5ba4f50e8590.png)

**Comment by athif23** [comment]
Didn't they already had the logo on them? It don't show up? I'm sure I added it.

**Comment by scanf** [comment]
If you take a closer look at the imba logo files you can see they are empty so they won't render as images. 

- [parcel-template](https://github.com/athif23/start-imba/blob/master/src/templates/parcel-template/public/imba-logo.png)
- [webpack-template](https://github.com/athif23/start-imba/blob/master/src/templates/webpack-template/public/imba-logo.png)

<img width="746" alt="Screen Shot 2019-09-22 at 10 02 22" src="https://user-images.githubusercontent.com/925044/65384234-1e62e380-dd20-11e9-84ca-8b2aca963ee4.png">

**Comment by athif23** [comment]
Fixed, see [v0.2.0](https://github.com/athif23/start-imba/releases/tag/v0.2.0).
