### ISSUE TITLE
Create a public npm package

### ISSUE THREAD

**Issue by scanf** [athif23/start-imba#2]
It's not hard to install this via `git clone ... && cd ... && npm install -g ./` but for convenience it would be nice to just run one command `npm install -g imba-start`.

**Comment by shapkarin** [comment]
I also thinking why it’s not published 🤔

**Comment by koolamusic** [comment]
Following up on these, what are the requirements to have this published to `npm` and Is there a way the community can help to make this happen ?

**Comment by athif23** [comment]
It's not completed yet, or more like I'm not satisfied with how it is. I actually have an almost completed version of it, but it's in my local repo, I'm trying to clean and fix a little bit of code, and push it. Also, maybe I would publish it to npm today. We will see.

**Comment by athif23** [comment]
Done. @koolamusic you can add it now. I just published this to npm, hope it works fine.
