### ISSUE TITLE
Option to pick a CSS framework

### ISSUE THREAD

**Issue by scanf** [athif23/start-imba#3]
I guess this could go under the todo item ` Add more feature like create-react-app or vue-cli.` but wanted to open a issue on this because IMHO it makes using `start-imba` much nicer for beginners when you can easily include any CSS framework you want similar to what [create nuxt-app][0] does, see screenshot below

![Screenshot 2019-06-22 at 12 00 27](https://user-images.githubusercontent.com/925044/59962418-8a496c00-94e5-11e9-84cf-4ab2db2579ba.png)

[0]: https://nuxtjs.org/guide/installation/

**Comment by athif23** [comment]
But well, I don't think Imba have css-framework at the moment. I don't know, if I found some, I would surely add it. Thanks.

**Comment by scanf** [comment]
Yeah, but I was thinking of adding options to the project templates. This way the user could select if they wanted to use SASS, LESS, vanilla CSS, etc. and it would be added in the index.html and appropriate loader for webpack / parcel.

Anyways, I am looking into CSS components for Imba this week maybe I will purpose something concrete as a pull request if I get time.

Thanks.

**Comment by athif23** [comment]
I see, yeah cool feel free to PR. I get some project to do(and yeah, it uses imba) right now, so wouldn't have time to work more on this.

**Comment by athif23** [comment]
Actually just published the newer version, there's LESS, SASS/SCSS, Stylus, and even Normal CSS options now. See [v0.2.0](https://github.com/athif23/start-imba/releases/tag/v0.2.0). I will close this now :)

**Comment by scanf** [comment]
@athif23 👍  really cool 🚀
