### ISSUE TITLE
Generate files from templates

### ISSUE THREAD

**Issue by shapkarin** [athif23/start-imba#4]
Hi. Actually it's not an issue at all :-) I just want to share with you that if you are want to generate files  it's nice to use `yeoman` way.  They use https://github.com/SBoudrias/mem-fs-editor#copytplfrom-to-context-templateoptions--copyoptions that lets you to use `ejs` template engine
I was find out that wile I was research for that https://github.com/shapkarin/redux-scaffolder/issues/1

**Comment by athif23** [comment]
Thanks. I have found a way to do that, and I think it works pretty nice.
