### ISSUE TITLE
Document the imba version in use

### ISSUE THREAD

**Issue by scanf** [athif23/start-imba#8]
Hei, 

I was looking at the [pkg.js](https://github.com/athif23/start-imba/blob/master/src/shared-utils/pkg.js) and it looks like you are not using the official Imba version for the parcel and a old Imba version for webpack. Why is that the case?

```javascript
exports.parcelPkg = {
[...]
	dependencies: {
		'imba': 'github:pushqrdx/imba'
	},
[...]
	devDependencies: {
		'sass': '^1.16.1',
		'parcel-bundler': '^1.10.3',
		'parcel-plugin-imba': 'github:shreeve/parcel-plugin-imba'
	}
}

exports.webpackPkg = {
[...]
	dependencies: {
	    "imba": "1.4.1",
		"css-loader": "^1.0.1",
	    "extract-text-webpack-plugin": "^4.0.0-beta.0",
	    "normalize-scss": "^7.0.1",
	    "style-loader": "^0.23.1",
	    "webpack-dev-server": "^3.1.10"
	},
	devDependencies: {
		"node-sass": "^4.10.0",
	    "sass-loader": "^7.1.0",
	    "webpack": "^4.26.0",
	    "webpack-cli": "^3.1.2"
	}
}
```

**Comment by athif23** [comment]
Oh, I forgot to change. The case is, @pushqrdx imba repo, has some update that I think people would like to use, but I don't think that's needed right now. Thanks for telling me.

**Comment by athif23** [comment]
Just published the new version, I would close this now.
