### ISSUE TITLE
Add option to choose different SCSS, SASS, vanilla CSS

### ISSUE THREAD

**Issue by iamtirado** [athif23/start-imba#9]
I love how easy it is to start a project, thanks so much.  But I use SASS instead of SCSS. I had to around switching the webpack config to make it work.

You could add this to webpack config: `test: /\.(sass|scss)$/` so that it can take either .sass or .scss files. Or make a CLI option that would set it up with `.sass`

**Comment by athif23** [comment]
Yeah, I plan to do that. Wait for it :)

**Comment by athif23** [comment]
I just published the [latest](https://github.com/athif23/start-imba/releases/tag/v0.2.0) version, you can use it now.
